name: Build and Deploy Docker Images

on:
  push:
    branches: [dev, main]
    paths:
      - 'web-app/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./web-app/frontend
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/apopulis-frontend:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./web-app/backend
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/apopulis-backend:latest
