name: Build and Deploy Docker Images

on:
  push:
    branches: [dev, main]  # Trigger on pushes to dev and main branches
    paths:
      - 'web-app/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./web-app/frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/apopulis-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/apopulis-frontend:latest
          cache-to: type=inline

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./web-app/backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/apopulis-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/apopulis-backend:latest
          cache-to: type=inline

#      - name: Send webhook to Azure VM
#        uses: distributhor/workflow-webhook@v3
#        with:
#          url: ${{ secrets.WEBHOOK_URL }}
#          method: POST
#          headers: |
#            Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}
